require 'mystro-common'
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

Mystro::Log.console_debug

# Set @@variable_name in a before(:all) block and give access to it
# via let(:variable_name)
#
# Example:
# describe Transaction do
#   set(:transaction) { Factory(:transaction) }
#
#   it "should be in progress" do
#     transaction.state.should == 'in_progress'
#   end
# end
def set(variable_name, &block)
  before(:all) do
    self.class.send(:class_variable_set, "@@#{variable_name}".to_sym, instance_eval(&block))
  end

  let(variable_name) do
    self.class.send(:class_variable_get, "@@#{variable_name}".to_sym).tap do |i|
      if i.respond_to?(:new_record?)
        i.reload unless i.new_record?
      end
    end
  end
end
