require 'mystro-common'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
Dir["./spec/support/**/*.rb"].sort.each {|f| require f}

#Mystro::Log.console_debug

def load_config(provider, type)
  c = YAML.load_file('test/config.yml')
  raise "missing configuration: #{provider.inspect} #{type.inspect}" unless c[provider] && c[provider][type]
  c[provider][type]
end

def connect(provider, type)
  cfg = load_config(provider, type)
  pn = provider
  opt = cfg['provider']||{}
  data = cfg['config']||{}
  Mystro::Cloud.new(pn, type, {options: opt, config: data})
end
